### ISSUE TITLE
build association on BraintreeRails::Customer doesn't exist

### ISSUE THREAD

**Issue by ravishanker** [lyang/braintree-rails-example#1]
In Customers Controller the build method used in create action 

```
@customer = BraintreeRails::Customer.build(params[:customer])
```

I had to change it to new to make it work.  I'm not sure if the association exists to use build method

```
@customer = BraintreeRails::Customer.new(params[:customer])
```

Look forward to fix.  Thanks

**Comment by lyang** [comment]
Hi Ravi,
Thanks for the feedback. I've fixed the missing alias for :build in braintree-rails.

To get the fixes in the example app, you can do

bundle update braintree-rails

Thanks

**Comment by ravishanker** [comment]
Thanks for prompt response. :+1:   Why do you need an alias for :new?
