### ISSUE TITLE
can't modify frozen BraintreeRails::Transaction

### ISSUE THREAD

**Issue by ravishanker** [lyang/braintree-rails-example#2]
Transactions actions submit, void and refund are throwing exception
#### can't modify frozen BraintreeRails::Transaction

I'm not sure if you have tested these operations (submit_for_settlement, void and refund).  It's not working for me.

**Comment by lyang** [comment]
Hi Ravi,

Thanks for the feedback.

I've fixed this in BraintreeRails repo, `bundle update braintree-rails` should fix this for you.

The intention of the freezing a transaction is, in reality you can't change any of its attributes after creation. You can only change it's status according to the rules. It seems I did missed some test cases. Sorry about that.

I've removed the freeze for the moment. I will figure out a better way to handle this.

Thanks for your feedback.

**Comment by ravishanker** [comment]
Thanks for prompt response.  It's working now.  Hope you can figure out a better way to handle transaction
