### ISSUE TITLE
merchant_id needs to be set

### ISSUE THREAD

**Issue by jtreanor** [lyang/braintree-rails-example#3]
Hey!

The TransactionsController gives me the error: "Braintree::Configuration.merchant_id needs to be set"

I have put my sandbox details as described in the readme into both config/braintree.rd and config/initializers/braintree.rb

Have you any idea why it's not picking up my config?

James.

**Comment by lyang** [comment]
1) The place to put the credentials is in config/initializers/braintree.rb.
2) You can put your credentials in plain text in it,

```
Braintree::Configuration.merchant_id = "your_merchant_id"
Braintree::Configuration.public_key = "your_public_key"
Braintree::Configuration.private_key = "your_private_key"
```

3) Or, you can put your credentials in environment variables (Note: those variable names are all upper case)

```
Braintree::Configuration.merchant_id = ENV['MERCHANT_ID']
Braintree::Configuration.public_key = ENV['PUBLIC_KEY']
Braintree::Configuration.private_key = ENV['PRIVATE_KEY']
```

E.g

```
export MERCHANT_ID="your_merchant_id"
export PUBLIC_KEY="your_public_key"
export PRIVATE_KEY="your_private_key"
rails server
```

Note, you need to restart the rails server for it to pick up the changed initializers.

You can test your credentials using

```
rails console
```

Then try

```
Braintree::Configuration.merchant_id
```

See if the configuration has been picked up by rails.

**Comment by jtreanor** [comment]
Thanks a million. Thats working now. Great project by the way! :)

**Comment by lyang** [comment]
You are welcome :)

**Comment by stevenkolstad** [comment]
Excellent codebase for the Braintree API! However, when I run rake spec, I still do get this message.

``` ruby
Failures:

  1) Address Management shows a list of addresses of given customer
     Failure/Error: Unable to find matching line from backtrace
     Braintree::ConfigurationError:
       Braintree::Configuration.merchant_id needs to be set
     # ./spec/support/braintree_integration/utils.rb:4:in `create_customer_for'
     # ./spec/support/braintree_integration/setup.rb:11:in `braintree_integration_setup_test_data'
     # ./spec/support/braintree_integration/setup.rb:34:in `block in included'

Finished in 29.71 seconds
24 examples, 12 failures
```

I've set the variables same as above, and even in .spec_helper.rb file. Whether a value is set in there or not this message comes up with multiple failures. If I run the console test in all environments the value comes back correct. Firefox pops open and reloads a number of windows that say login to braintree sandbox failed.

The actions I performed run perfect from the console and browser. I'm trying this against Rails 4.0.4 & Ruby 2.1.1.

**Comment by lyang** [comment]
Hi @stevenkolstad ,
I can't seem to reproduce the issue.
Currently the configurations are set in `config/initializers/braintree.rb` from environment variables.

As for those Firefox windows, the test tries to login to the Braintree sandbox control panel and purges all sandbox data so that it keeps the test environment clean.

Can you try to inspect the merchant_id in your `initializer.rb` and `spec_helper.rb` when running the test?

Thanks

**Comment by mwathi** [comment]
@lyang thanks, your answer helped me out as well
