### ISSUE TITLE
CC Number and CVV can't be blank

### ISSUE THREAD

**Issue by vedanova** [lyang/braintree-rails-example#4]
I've just downloaded the example and ran it locally.

For whatever reason the Number and CVV are filtered out when trying to add a new Credit Card and therefore I get the validation errors.

Copied the code over to my real application and I do experience the same.

To replicate:
Clone the repo, add a new gemset in rvm , bundle install, rake migrate, add api keys.

Thanks

**Comment by vedanova** [comment]
Figured it out, I didn't set the client encryption key.

Would be good if you would add that to the Readme.

Thanks for this great gem!

**Comment by lyang** [comment]
Hi @vedanova ,
Thanks for the feedback, I will add that to the Readme file.
Glad you like it :-)
