### ISSUE TITLE
Transparent Redirect

### ISSUE THREAD

**Issue by creativecommunion** [lyang/braintree-rails-example#5]
Create controller and views to take advantage of Transparent Redirect. https://www.braintreepayments.com/docs/ruby/credit_cards/create_tr

**Comment by lyang** [comment]
Hi @creativecommunion ,
There's a [transparent redirect branch](https://github.com/lyang/braintree-rails-example/tree/transparent_redirect) that has the TR implementation.

However TR implementation is deprecated in favor of Braintree.js implementation.

Personally I feel using S2S with [braintree.js](https://www.braintreepayments.com/braintrust/braintree-js) has both the advantage of greatly reduced PCI compliance scope of TR and the greater control and flexibility of S2S.

Thanks
