### ISSUE TITLE
Missing Models

### ISSUE THREAD

**Issue by brandonmikeska** [lyang/braintree-rails-example#7]
Are all the models present in this example? I am trying to get this working with mongoid 4 and don't see your structure for your Subscription and Transaction model. Are they encapsulated in the gem or did you just not include them in the example?

**Comment by lyang** [comment]
Hi @brandonmikeska,
Sorry for a late response, just got back from vacation.

All models are defined in the gem, and they are just plain ruby object. Those models wrap the [braintree_ruby](https://github.com/braintree/braintree_ruby) objects and provide a ActiveModel compatible interface.

**Comment by brandonmikeska** [comment]
Oh ok thanks!
