### ISSUE TITLE
Uber Style Payment Method

### ISSUE THREAD

**Issue by RailsCod3rFuture** [lyang/braintree-rails-example#8]
Do you know which strategy has the shared payment feature? I see that yours has the Plans, Subscriptions and Transactions Controller. I just don't know how to go about implementing the marketplace strategy.

**Comment by lyang** [comment]
Hi @RailsCod3rFuture ,
According to [Quora](http://www.quora.com/How-does-Uber-pay-drivers), Uber collects all the payment from consumers and then do direct deposit to its drivers once a week. So Uber is not sharing the payment via Braintree's API on a per transaction basis.

As for Marketplace merchants, you need to first [onboard your sub-merchant](https://developers.braintreepayments.com/javascript+ruby/guides/marketplace/onboarding), and then [create transaction with service fees](https://developers.braintreepayments.com/javascript+ruby/guides/marketplace/create) using the sub-merchant's id.

You can also take a look at the [overview](https://developers.braintreepayments.com/javascript+ruby/guides/marketplace/overview) of the Braintree Marketplace feature.

You can [create/update sub-merchant](https://github.com/lyang/braintree-rails/blob/master/spec/integration/braintree_rails/merchant_account_integration_spec.rb), but note that the approval confirmation needs you to setup an endpoint to receive the [webhook](https://developers.braintreepayments.com/javascript+ruby/guides/marketplace/confirmation).

Then you can merge in an additional `service_fee_amount` param when [creating transaction](https://github.com/lyang/braintree-rails-example/blob/master/app/controllers/transactions_controller.rb#L16).

I will see if this is something I can demo in this example app on Heroku when time permits.

At the mean time, feel free to contact 877.434.2894 or support@braintreepayments.com if you have any questions.

**Comment by RailsCod3rFuture** [comment]
Thanks for helping me figure this out, and I'll be looking forward to anything that you come up with in the near future.
